### PR TITLE
Updated .same to .deepEqual

### PR DESCRIPTION
**Pull request by bones7242**
`.same` does not seem to be supported.  I changed it to `.deepEqual`.

### CODE REVIEW

**Review by lukeed — APPROVED** [review]
It's been a long time 😆 The API changed. Thank you!

**Comment by lukeed** [comment]
There's actually a lot to be done here -- the entire module dev-env is outdated.

I'll merge (thanks!) but will need to do more cleanup.

**Comment by bones7242** [comment]
Let me know if I can help.  Very useful package.  Thanks for making it!

**Comment by lukeed** [comment]
Went ahead & updated everything, as well as pushing out a 1.0~! But thank you for the offer 🙇

**Pull request merged**
